/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare class VectorContext {
  constructor(tolerance?: number | undefined | null)
  pushTransform(matrix: Array<number>): void
  popTransform(): void
  setWorldTransform(matrix: Array<number>): void
  beginPath(): void
  moveTo(x: number, y: number): void
  lineTo(x: number, y: number): void
  quadTo(cx: number, cy: number, x: number, y: number): void
  cubicTo(c1X: number, c1Y: number, c2X: number, c2Y: number, x: number, y: number): void
  arc(cx: number, cy: number, radius: number, startAngle: number, sweepAngle: number): void
  closePath(): void
  fill(r: number, g: number, b: number, a: number): void
  stroke(r: number, g: number, b: number, a: number, width: number): void
  loadFont(name: string, path: string, faceIndex?: number | undefined | null): void
  unloadFont(name: string): void
  drawText(text: string, fontName: string, sizePx: number, x: number, y: number): void
  fontMetrics(fontName: string, sizePx: number): FontMetrics
  measureText(fontName: string, sizePx: number, text: string): number
  flush(): FlushOutput
  clear(): void
}

export interface FlushOutput {
  vertices: Float32Array
  indices: Uint32Array
  drawCalls: Array<GpuDrawCall>
}

export interface FontMetrics {
  ascender: number
  descender: number
  lineGap: number
  lineHeight: number
  capHeight: number
  xHeight: number
  unitsPerEm: number
}

export interface GpuDrawCall {
  firstIndex: number
  indexCount: number
  modelMatrix: Float32Array
}
